trigger: none

pr: none

variables:
  - name: devEnvironment
    value: WRKSHP_IS_LogicApp_dev_classic_app
  - name: serviceConnection
    value: "WRKSHP_IS_ME-MngEnvMCAP675646-emknafo-1 (64c3d212-40ed-4c6d-a825-6adfbdf25dad)-4734"

resources:
  pipelines:
    - pipeline: cipipeline
      # TODO: Update with the name of your CI pipeline
      source: "\\Workshops\\Accelerating Innovation With Integration Services\\WRKSHP_LogicApps-ci-pipe"
      trigger:
        branches:
          - main

stages:
  - stage: DEV
    displayName: "DEV Deployment"
    variables:
      - template: variables/pipeline-vars.yml
    jobs:
      - deployment: deploy_logicapp_resources
        displayName: Deploy Logic App
        pool:
          vmImage: ubuntu-latest
        environment: $(devEnvironment)
        variables:
          deploymentMode: "Incremental"
        strategy:
          runOnce:
            deploy:
              steps:
                # list files in the pipeline workspace
                - script: |
                    ls -R $(Pipeline.Workspace)/cipipeline
                  displayName: "List files in pipeline workspace"
                - task: AzureFunctionApp@1
                  displayName: "Deploy logic app workflows"
                  inputs:
                    # TODO: Fill in with the name of your Azure service connection
                    azureSubscription: "$(serviceConnection)"
                    appType: "functionApp"
                    appName: "$(logicAppName)"
                    package: "$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip"
                    deploymentMethod: "zipDeploy"
