trigger: none

pr: none

variables:
  - name: artifactName
    value: deploy_artifacts
  - name: devEnvironment
    value: WRKSHP_IS_LogicApp_dev
  - name: vmImage
    value: ubuntu-latest
  - name: armSourceFolder
    value: src/azure-devops-sample/deploy
  - name: serviceConnection
    value: "WRKSHP_IS_ME-MngEnvMCAP675646-emknafo-1 (64c3d212-40ed-4c6d-a825-6adfbdf25dad)-4734"

stages:
  - stage: Builds
    displayName: "Publish IaC Artifacts"
    jobs:
      - job: Build
        pool:
          vmImage: $(vmImage)
        steps:
          - task: CopyFiles@2
            displayName: "Copy ARM templates"
            inputs:
              sourceFolder: "$(armSourceFolder)"
              targetFolder: "$(Build.ArtifactStagingDirectory)"
          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: $(artifactName)
  - stage: DEV
    displayName: "DEV Deployment"
    variables:
      - template: variables/pipeline-vars.yml
    jobs:
      - template: templates/template-iac-logicapp.yml
        parameters:
          environment: $(devEnvironment)
          # TODO: Fill in with the name of your Azure service connection
          serviceConnection: "$(serviceConnection)"
