trigger: none

pr: none

variables:
  - name: devEnvironment
    value: WRKSHP_IS_LogicApp_dev_006
  - name: vmImage
    value: ubuntu-latest
  - name: serviceConnection
    value: "WRKSHP_IS_ME-MngEnvMCAP675646-emknafo-1 (64c3d212-40ed-4c6d-a825-6adfbdf25dad)-4734"
  - name: resourceGroupName
    value: "rg-iac-pipeline-006"
  - name: resourceGroupLocation
    value: "canadacentral"
  - name: templateFile
    value: infra/main.bicep
  - name: deploymentName
    value: "iac-deployment-006"
  - name: projectFile
    value: "src/logic-vvihbnryoetdu/logic-vvihbnryoetdu.csproj"

stages:
  - stage: Build
    displayName: "Build"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: self
          # build and deploy logic app in dotnet 6
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk 6.x"
            inputs:
              packageType: "sdk"
              version: "6.x"
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: dotnet build $(projectFile)
            displayName: "Build Logic App"
          - script: dotnet publish $(projectFile) --output $(Build.ArtifactStagingDirectory)
            displayName: "Publish Logic App"
          # publish artifact
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact"
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: "logic-app"
              publishLocation: "Container"
  - stage: DeployInfra
    displayName: "Deploy Infrastructure"
    dependsOn: Build
    jobs:
      - deployment: DeployInfraJob
        displayName: "Deploy Infrastructure Job"
        pool:
          vmImage: $(vmImage)
        environment: $(devEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # azure cli task to login to azure
                - task: AzureCLI@2
                  displayName: "deploy infrastructure using bicep"
                  inputs:
                    azureSubscription: "$(serviceConnection)"
                    scriptType: "pscore"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az account show
                      az group create --name $(resourceGroupName) `
                        --location $(resourceGroupLocation)
                      # deploy
                      az deployment group create --resource-group $(resourceGroupName) `
                        --template-file $(templateFile) `
                        --name $(deploymentName)
