# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - func-ek0XX

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      instanceNumber:
        description: "Unique suffix for resource names"
        required: true
        default: "009"

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "src/logic-vvihbnryoetdu" # set this to the path to your web app project, defaults to the repository root
  #DOTNET_VERSION: "6.0.x" # set this to the dotnet version to use
  DOTNET_VERSION: "8.0.x" # set this to the dotnet version to use
  RESOURCE_GROUP: "rg-iac-pipeline-${{ inputs.instanceNumber }}" # set this to your Azure Resource Group name
  LOCATION: "canadacentral" # set this to the Azure region where your resources will be deployed
  NAME_SUFFIX: "${{ inputs.instanceNumber }}" # set this to a unique suffix for resource names
  DEPLOYMENT_NAME: "iac-deployment-${{ inputs.instanceNumber }}" # set this to the name of your deployment

# Permission can be added at job level or workflow level
permissions:
  id-token: write #This is required for requesting the JWT
  contents: write # This is required to create/push the new git tag

jobs:
  deploy-infra:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: write # This is required to create/push the new git tag
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # run powershell core script Deploy-Infrastructure.ps1
      - name: Deploy Infrastructure
        shell: pwsh
        run: |
          ./New-Deployment.ps1 -location "${{ env.LOCATION }}" `
            -instanceNumber "${{ env.NAME_SUFFIX }}"
  build-and-deploy:
    runs-on: windows-latest
    needs: deploy-infra
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: write # This is required to create/push the new git tag
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
      - name: Display GitVersion outputs
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
      - name: Create tag
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.gitversion.outputs.semVer }}",
              sha: context.sha
            })
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output -p:Version=${{ steps.gitversion.outputs.semVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }}
          popd
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # get the Logic App name from deployment output
      - name: Get Logic App Name
        id: get_app_name
        run: |
          # get logic app name
          $logicAppName = az deployment group show --resource-group ${{ env.RESOURCE_GROUP }} `
                        --name ${{ env.DEPLOYMENT_NAME }} `
                        --query properties.outputs.logicAppName.value `
                        -o tsv
          echo "Logic App Name: $logicAppName"
          # set the logic app name as an environment variable
          #echo "AZURE_FUNCTIONAPP_NAME=$logicAppName" >> $GITHUB_ENV
          echo "AZURE_FUNCTIONAPP_NAME=$logicAppName" | Out-File -FilePath $env:GITHUB_ENV -Append
      # deploy logic app
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "${{ env.AZURE_FUNCTIONAPP_NAME }}"
          slot-name: "Production"
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
  validate-deployment:
    runs-on: windows-latest
    needs: build-and-deploy
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: write # This is required to create/push the new git tag
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # run powershell core script Validate-Deployment.ps1
      - name: Validate Deployment
        shell: pwsh
        run: |
          ./Validate-Deployment.ps1 -instanceNumber "${{ env.NAME_SUFFIX }}"
